// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class confirm_email_property_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confirm_email_property_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201710280717478_confirm_email_property_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
