// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class card_number_set_to_null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(card_number_set_to_null));
        
        string IMigrationMetadata.Id
        {
            get { return "201710171646518_card_number_set_to_null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
